-- ----------------------------------------------------------------------------------------
-- Gabriel Issa Shammas (GIS) - 01 de janeiro de 2000 a 31 de dezembro de 2020
-- ----------------------------------------------------------------------------------------
-- CALC0001- GIS_TB01S005_CONTINENTE
--
-- Calcular o tamanho da tupla desta tabela, em bytes.
--
-- ----------------------------------------------------------------------------------------
-- Resposta.
-- ----------------------------------------------------------------------------------------
--
-- A tupla é o conjunto de colunas, logo, basta somar a quantidade de bytes de cada  coluna
-- e teremos a quantidade de bytes da linha (ou da tupla).
--
-- Assim: 3 + 50 + 3 + 11 + 72 = 139 bytes.
--
-- Então, a tupla desta tabela possui 139 bytes.
--
-- ----------------------------------------------------------------------------------------
-- Comentários.
-- ----------------------------------------------------------------------------------------
--
-- Para coluna com tipo de dado  NUMERIC (2, 0), consideramos tamanho de 2 bytes.
--
-- Para coluna com tipo de dado  NUMERIC (11, 2), consideramos tamanho de 11 bytes.
--
-- Para coluna com tipo de dado  CHAR (5), consideramos tamanho de 5 bytes.
--
-- Para coluna com tipo de dado  VARCHAR (20), consideramos tamanho de 20 bytes.
--
-- Para coluna com tipo de dado  INT (Integer), consideramos tamanho de 4 bytes.
--
-- Para coluna com tipo de dado  SMALLINT (Small Integer), consideramos tamanho de 2 bytes.
--
-- Para coluna com tipo de dado  DATETIME, consideramos tamanho de 8 bytes.
--
-- Para coluna com tipo de dado  DATE, consideramos tamanho de 4 bytes.
--
-- Para coluna com tipo de dado  TIME, consideramos tamanho de 4 bytes.
--
-- Para colunas com tipo de dados NUMERIC ou DECIMAL, não estamos considerando as  técnicas
-- de compactação de campos numéricos, que pode variar conforme o fabricante.
--
-- Para colunas com tipo de dados  VARCHAR ou VARINT, não estamos considerando  os bytes a-
-- dicionais para cada coluna de tamanho variável.
--
-- Para colunas que aceitam o valor  NULL, não estamos considerando os bytes adicionais pa-
-- ra cada coluna com valor nulo.
--
-- Para efeito de esclarecimento inicial no cálculo do tamanho da tupla, consideramos  ape-
-- nas os valores nominais das colunas.
--
-- ----------------------------------------------------------------------------------------
-- Fim TB01S005 CALC0001
-- ----------------------------------------------------------------------------------------
--
--
