-- ----------------------------------------------------------------------------------------
-- Gabriel Issa Shammas (GIS) - 01 de janeiro de 2000 a 31 de dezembro de 2020
-- ----------------------------------------------------------------------------------------
-- TEOR0005- GIS_TB01S005_CONTINENTE
--
-- Esta tabela possui Índice Primário (IP) (Primary Index)? Explique.
--
-- ----------------------------------------------------------------------------------------
-- Resposta.
-- ----------------------------------------------------------------------------------------
--
-- Sim.
-- Esta tabela possui Índice Primário (IP) (Primary Index) porque a tabela foi  criada  com
-- a definição de uma  Chave Primária (Primary Key ou PK)  e o Índice Primário (IP) é cons-
-- truído sobre a Chave Primária.
--
-- ----------------------------------------------------------------------------------------
-- Fim TB01S005 TEOR0005
-- ----------------------------------------------------------------------------------------
--
--
