-- ----------------------------------------------------------------------------------------
-- Gabriel Issa Shammas (GIS) - 01 de janeiro de 2000 a 31 de dezembro de 2020
-- ----------------------------------------------------------------------------------------
-- QUERY060- GIS_TB01S005_CONTINENTE
--
-- Quais são os continentes cuja coluna observação (obs) encontra-se com valor nulo?
-- Atenção: Exibir os dados, colocando na primeira coluna a data e a hora conforme  o Meri-
--          diano de Greenwich ou data e hora de Londres  (ou UTC- Universal Time Coordina-
--          te).
--          Na segunda coluna colocar a data e a hora correntes (ou seja, a data e hora lo-
--          cais ou de Brasília).
--          Colocar uma coluna de separação entre a data corrente e os demais dados, de mo-
--          do que o nome desta coluna fique em branco.
--
-- ----------------------------------------------------------------------------------------
-- Fim TB01S005 QUERY060
-- ----------------------------------------------------------------------------------------
--
--
