-- ----------------------------------------------------------------------------------------
-- Gabriel Issa Shammas (GIS) - 01 de janeiro de 2000 a 31 de dezembro de 2020
-- ----------------------------------------------------------------------------------------
-- IX000002- GIS_TB01S005_CONTINENTE
--
-- Criar novamente o índice secundário  de nome  IX_GIS_TB01S005_CONTINENTE_SIGLA,  sobre a
-- coluna SIGLA, com ordenação crescente e com Fill Factor = 10%.
--
-- Desta vez, não informar a opção de eliminação do índice.
--
-- Atenção:
-- Caso ocorra um erro, explicar a razão do mesmo e, em seguida,  efetuar  as correções que
-- que se fizerem necessárias.
--
-- ----------------------------------------------------------------------------------------
-- Fim TB01S005 IX000002
-- ----------------------------------------------------------------------------------------
--
--
