-- ----------------------------------------------------------------------------------------
-- Gabriel Issa Shammas (GIS) - 01 de janeiro de 2000 a 31 de dezembro de 2020
-- ----------------------------------------------------------------------------------------
-- QUERY057- GIS_TB01S005_CONTINENTE
--
-- Quais são os continentes cuja coluna observação (obs) encontra-se com valor nulo?
-- Atenção: Exibir os dados, colocando na primeira coluna a Data e a Hora correntes (ou se-
-- ja, a data e hora locais ou data e hora de Brasília).
--
-- ----------------------------------------------------------------------------------------
-- Fim TB01S005 QUERY057
-- ----------------------------------------------------------------------------------------
--
--
