-- ----------------------------------------------------------------------------------------
-- Gabriel Issa Shammas (GIS) - 01 de janeiro de 2000 a 31 de dezembro de 2020
-- ----------------------------------------------------------------------------------------
-- QUERY026- GIS_TB01S005_CONTINENTE
--
-- Mostrar o valor binário da soma de verificação calculado para cada linha de tabela.
-- Atenção: Colocar label (rótulo) na coluna resultante.
--
-- ----------------------------------------------------------------------------------------
-- Fim TB01S005 QUERY026
-- ----------------------------------------------------------------------------------------
--
--
