-- ----------------------------------------------------------------------------------------
-- Gabriel Issa Shammas (GIS) - 01 de janeiro de 2000 a 31 de dezembro de 2020
-- ----------------------------------------------------------------------------------------
-- QUERY023- GIS_TB01S005_CONTINENTE
--
-- Qual é o desvio padrão da superfície dos continentes?
-- Atenção: Colocar label (rótulo) na coluna resultante.
-- Atenção: Não usar a função STDEV, mas sim STDEVP.
--
-- ----------------------------------------------------------------------------------------
-- Fim TB01S005 QUERY023
-- ----------------------------------------------------------------------------------------
--
--
