-- ----------------------------------------------------------------------------------------
-- Gabriel Issa Shammas (GIS) - 01 de janeiro de 2000 a 31 de dezembro de 2020
-- ----------------------------------------------------------------------------------------
-- QUERY021- GIS_TB02S002_SUB_CONTINENTE
--
-- Quantos são os subcontinentes existentes?
-- Atenção: Colocar label (rótulo) nas colunas resultantes.
-- Atenção: Imprimir também:
--          Qual é a soma das áreas de todos os subcontinentes?
--          Qual é a média das áreas de todos os subcontinentes?
--          Qual é a maior área de um subcontinente?
--          Qual é a menor área de um subcontinente?
--          Qual é o desvio padrão da área de todos os subcontinentes?
--          Qual é a variância da área de todos os subcontinentes?
-- Atenção: Exibir como primeira coluna da tupla a data/hora do sistema (ou data/hora local
--          ou data/hora de Brasília), separada das demais colunas por um "-" (hífen).
-- Atenção: Exibir como terceira coluna da tupla  a  data/hora universal  (ou  data/hora de
--          Greenwich ou data/hora de Londres), separada das demais colunas por um "-" (hí-
--          fen).
--
-- ----------------------------------------------------------------------------------------
-- Fim TB02S002 QUERY021
-- ----------------------------------------------------------------------------------------
--
--
