-- ----------------------------------------------------------------------------------------
-- Gabriel Issa Shammas (GIS) - 01 de janeiro de 2000 a 31 de dezembro de 2020
-- ----------------------------------------------------------------------------------------
-- QUERY022- GIS_TB02S002_SUB_CONTINENTE
--
-- Quais são os subcontinentes do continente de código igual a 1?
-- Atenção: Ordenar a saída pelo nome do subcontinente, em ordem decrescente.
--
-- ----------------------------------------------------------------------------------------
-- Fim TB02S002 QUERY022
-- ----------------------------------------------------------------------------------------
--
--
