-- ----------------------------------------------------------------------------------------
-- Gabriel Issa Shammas (GIS) - 01 de janeiro de 2000 a 31 de dezembro de 2020
-- ----------------------------------------------------------------------------------------
-- QUERY023- GIS_TB02S002_SUB_CONTINENTE
--
-- Selecionar todos os subcontinentes, explicitando as colunas no comando e colocando label
-- nestas colunas, para que o usuário possa melhor entender o relatório gerado.
-- Atenção: Exibir apenas os subcontinentes do continente de nome "África".
--          O código desse continente não é conhecido por você.
--          Exibir o nome do continente ao lado do código do continente.
--          Ordenar a saída pelo nome do subcontinente, em ordem crescente.
-- Atenção: Usar o Join Natural (Natural Join).
--
-- ----------------------------------------------------------------------------------------
-- Fim TB02S002 QUERY023
-- ----------------------------------------------------------------------------------------
--
--
