-- ----------------------------------------------------------------------------------------
-- Gabriel Issa Shammas (GIS) - 01 de janeiro de 2000 a 31 de dezembro de 2020
-- ----------------------------------------------------------------------------------------
-- QUERY003- GIS_TB02S001_CONTINENTE_GENTILICO
--
-- Selecionar todos os gentílicos de continente, explicitando as colunas no comando e colo-
-- cando label nestas colunas, para que o usuário possa melhor entender o relatório gerado.
--
-- ----------------------------------------------------------------------------------------
-- Fim TB02S001 QUERY003
-- ----------------------------------------------------------------------------------------
--
--
