-- ----------------------------------------------------------------------------------------
-- Gabriel Issa Shammas (GIS) - 01 de janeiro de 2000 a 31 de dezembro de 2020
-- ----------------------------------------------------------------------------------------
-- QUERY040- GIS_TB03S001_PAISES
--
-- Qual é o total de países existentes?
-- Atenção: Observar com atenção como é o nome da coluna.
--
-- ----------------------------------------------------------------------------------------
-- Atenção. Indicação do BD a ser usado. Se for o caso, mude o nome do Banco.
-- ----------------------------------------------------------------------------------------
--
USE BDGIS;
--
-- ----------------------------------------------------------------------------------------
-- Seleção de todos os dados para visualização do conteúdo da tabela.
-- ----------------------------------------------------------------------------------------
--
Select count(*)
  From dbo.GIS_TB03S001_PAISES;
--
-- ----------------------------------------------------------------------------------------
-- Comentários.
-- ----------------------------------------------------------------------------------------
--
-- No comando SELECT, a tupla também pode ser elaborada com funções.
--
-- Dentre as funções disponíveis, encontram-se as funções de agregação, que englobam,  den-
-- tre outras, funções como COUNT(*), MAX, MIN, SUM e AVG.
--
-- As funções de agregação,  por não fazerem parte  da tabela,  são exibidas em colunas sem
-- nome.
--
-- ----------------------------------------------------------------------------------------
-- Fim TB03S001 QUERY040
-- ----------------------------------------------------------------------------------------
--
--
