-- ----------------------------------------------------------------------------------------
-- Gabriel Issa Shammas (GIS) - 01 de janeiro de 2000 a 31 de dezembro de 2020
-- ----------------------------------------------------------------------------------------
-- QUERY060- GIS_TB03S001_PAISES
--
-- Qual é a área média dos países da América e Ásia?
-- Atenção: Usar o predicado de lista no Select.
-- Atenção: Usar o predicado LIKE no Subselect.
-- Atenção: Esta é a mesma query anterior, mas com uma segunda solução.
--
-- ----------------------------------------------------------------------------------------
-- Fim TB03S001 QUERY060
-- ----------------------------------------------------------------------------------------
--
--
