-- ----------------------------------------------------------------------------------------
-- Gabriel Issa Shammas (GIS) - 01 de janeiro de 2000 a 31 de dezembro de 2020
-- ----------------------------------------------------------------------------------------
-- QUERY099- GIS_TB03S001_PAISES
--
-- Quais são os países cujo código esteja entre 20 e 23 (inclusive)?
-- Atenção: Colocar o nome do continente ao lado do código do continente.
-- Atenção: Colocar o nome do subcontinente ao lado do código do subcontinente.
-- Atenção: Usar Join Natural (Natural Join).
-- Atenção: Ordenar a saída pela coluna CODIGO, de modo decrescente.
--
-- ----------------------------------------------------------------------------------------
-- Fim TB03S001 QUERY099
-- ----------------------------------------------------------------------------------------
--
--
