-- ----------------------------------------------------------------------------------------
-- Gabriel Issa Shammas (GIS) - 01 de janeiro de 2000 a 31 de dezembro de 2020
-- ----------------------------------------------------------------------------------------
-- QUERY038- GIS_TB03S001_PAISES
--
-- Quais são os países cuja extensão territorial é maior do que o país com a menor extensão
-- territorial e é menor do que o país com a maior extensão territorial?
--
-- ----------------------------------------------------------------------------------------
-- Fim TB03S001 QUERY038
-- ----------------------------------------------------------------------------------------
--
--
