#GeoGebra Portable preferences (GeoGebra settings file)
#Tue Sep 17 12:55:18 BRT 2019
app_file_8=
app_file_7=
app_file_6=
app_file_5=
app_file_4=
app_file_3=
app_file_2=
app_file_1=Z\:\\Disciplinas\\Curso de An\u00E1lise e Desenvolvimento de Sistemas\\Matutino\\5\u00BA Ciclo\\Programa\u00E7\u00E3o Linear\\4_m\u00E9todo_gr\u00E1fico\\Exemplo_Resolu\u00E7ao_grafica.ggb
user_login_skip=true
