-- ----------------------------------------------------------------------------------------
-- Gabriel Issa Shammas (GIS) - 01 de janeiro de 2000 a 31 de dezembro de 2020
-- ----------------------------------------------------------------------------------------
-- QUERY015- GIS_TB01S005_CONTINENTE
--
-- Qual é o total de continentes existentes?
-- Atenção: Fazer a contagem a partir de uma coluna.
--          Por exemplo, utilizar a coluna  SIGLA  para a contagem de linhas (tuplas).
--
-- ----------------------------------------------------------------------------------------
-- Atenção. Indicação do BD a ser usado. Se for o caso, mude o nome do Banco.
-- ----------------------------------------------------------------------------------------
--
USE BDGIS;
--
-- ----------------------------------------------------------------------------------------
-- Seleção de todos os dados para visualização do conteúdo da tabela.
-- ----------------------------------------------------------------------------------------
--
Select count(sigla)  'Cardinalidade da tabela'
  From dbo.GIS_TB01S005_CONTINENTE;
--
-- ----------------------------------------------------------------------------------------
-- Comentários.
-- ----------------------------------------------------------------------------------------
--
-- A cláusula FROM é a única cláusula obrigatória no comando SELECT.
--
-- As Funções de Agregação são declaradas no comando SELECT  tal qual se faz com a declara-
-- ção de uma coluna.
--
-- Uma função de agregação, ao ser exibida, terá como nome de coluna  "COLUMN NO NAME",  ou
-- seja, "Coluna Sem Nome", porque sua origem não é da própria tabela.
--
-- Para evitar este nome de coluna, utiliza-se de um label ou rótulo de coluna.
--
-- Este comando retorna a cardinalidade da tabela, ou seja,  o total de tuplas  (ou linhas)
-- que a tabela possui.
--
-- ----------------------------------------------------------------------------------------
-- Fim TB01S005 QUERY015
-- ----------------------------------------------------------------------------------------
--
--
